import { compareTime, type MusicalTime } from '../musicxml/musicalTime'
import { REFERENCE_COMPARISON_ENGINE_VERSION, resolveReferenceComparisonOptions, type ReferenceComparisonOptions } from './options'
import type { InterpretationProfile, ReferenceComparisonReliability, ReferenceComparisonResult, ReferenceDifferenceObservation, ReferenceDimensionComparison, SimilarityDescriptor } from './types'

export interface CompareInterpretationsInput { readonly current: InterpretationProfile; readonly reference: InterpretationProfile | null; readonly currentVoicingAnalysisId: string; readonly options?: Partial<ReferenceComparisonOptions> }
function stableHash(value: string): string { let hash = 0x811c9dc5; for (let i = 0; i < value.length; i += 1) { hash ^= value.charCodeAt(i); hash = Math.imul(hash, 0x01000193) } return (hash >>> 0).toString(16).padStart(8, '0') }
function samePartSelection(left: readonly string[], right: readonly string[]): boolean { const canonical = (ids: readonly string[]) => [...new Set(ids)].sort(); const a = canonical(left); const b = canonical(right); return a.length === b.length && a.every((id, index) => id === b[index]) }
function deepFreeze<T>(value: T, seen = new WeakSet<object>()): T { if (value === null || typeof value !== 'object' || seen.has(value)) return value; seen.add(value); Object.values(value as Record<string, unknown>).forEach((child) => deepFreeze(child, seen)); return Object.freeze(value) }
function median(values: readonly number[]): number { const sorted = [...values].sort((a, b) => a - b); const i = Math.floor(sorted.length / 2); return sorted.length % 2 ? sorted[i]! : (sorted[i - 1]! + sorted[i]!) / 2 }
function within(position: MusicalTime, overlap: { start: MusicalTime | null; end: MusicalTime | null }): boolean { return (!overlap.start || compareTime(position, overlap.start) >= 0) && (!overlap.end || compareTime(position, overlap.end) <= 0) }
function rank(value: ReferenceComparisonReliability): number { return value === 'reliable' ? 3 : value === 'limited' ? 2 : value === 'provisional' ? 1 : 0 }
function combineReliability(left: string | null, right: string | null, shared: number, ratio: number, options: ReferenceComparisonOptions): ReferenceComparisonReliability { if (!left || !right || shared === 0) return 'unavailable'; if (left === 'unavailable' || right === 'unavailable') return 'unavailable'; if (left === 'provisional' || right === 'provisional') return 'provisional'; return shared < options.reliableMinimumSharedObservations || ratio < options.reliableMinimumCoverage || left === 'limited' || right === 'limited' ? 'limited' : 'reliable' }
function similarity(magnitude: number, similar: number, noticeable: number): SimilarityDescriptor { return magnitude <= similar / 2 ? 'very-similar' : magnitude <= similar ? 'similar' : magnitude <= noticeable ? 'noticeably-different' : 'strongly-different' }
function unavailable(reason: string): ReferenceDimensionComparison { return { status: 'unavailable', reliability: 'unavailable', unavailableReason: reason, coverage: { currentCount: 0, referenceCount: 0, sharedCount: 0, ratio: null }, observations: [], summary: reason } }
function observation(idPrefix: string, key: string, position: MusicalTime, measures: readonly string[], currentValue: number, referenceValue: number, similar: number, noticeable: number, describe: (difference: number, similarity: SimilarityDescriptor) => string): ReferenceDifferenceObservation { const signedDifference = currentValue - referenceValue; const magnitude = Math.abs(signedDifference); const descriptor = similarity(magnitude, similar, noticeable); return { id: `${idPrefix}:${stableHash(key)}`, key, position: { ...position }, measureNumbers: [...measures], currentValue, referenceValue, signedDifference, magnitude, similarity: descriptor, description: describe(signedDifference, descriptor) } }

function compareKeyed<T extends { key: string; position: MusicalTime }>(current: readonly T[] | null, reference: readonly T[] | null, overlap: { start: MusicalTime | null; end: MusicalTime | null }, values: (value: T) => number, measures: (value: T) => readonly string[], reliability: readonly [string | null, string | null], options: ReferenceComparisonOptions, label: string, describe: (difference: number, similarity: SimilarityDescriptor) => string, thresholds = [options.similarNormalizedDifference, options.noticeableNormalizedDifference]): ReferenceDimensionComparison {
  if (current === null || reference === null) return unavailable(`${label} evidence is absent from one historical attempt.`)
  const currentIn = current.filter((item) => within(item.position, overlap)); const referenceIn = reference.filter((item) => within(item.position, overlap)); const referenceByKey = new Map(referenceIn.map((item) => [item.key, item]))
  const observations = currentIn.flatMap((item) => { const other = referenceByKey.get(item.key); return other ? [observation(`reference-${label.toLowerCase()}`, item.key, item.position, measures(item), values(item), values(other), thresholds[0]!, thresholds[1]!, describe)] : [] }).sort((a, b) => compareTime(a.position, b.position) || a.key.localeCompare(b.key))
  const denominator = Math.max(currentIn.length, referenceIn.length); const ratio = denominator ? observations.length / denominator : null; const comparisonReliability = combineReliability(reliability[0], reliability[1], observations.length, ratio ?? 0, options)
  if (!observations.length) return unavailable(`No shared ${label.toLowerCase()} evidence exists in the overlapping score region.`)
  const averageMagnitude = observations.reduce((sum, item) => sum + item.magnitude, 0) / observations.length
  return { status: 'ready', reliability: comparisonReliability, unavailableReason: null, coverage: { currentCount: currentIn.length, referenceCount: referenceIn.length, sharedCount: observations.length, ratio }, observations, summary: averageMagnitude <= thresholds[0]! ? `${label} is similar across the shared evidence.` : `${label} differs across parts of the shared score region.` }
}

function compareTempo(current: InterpretationProfile, reference: InterpretationProfile, overlap: { start: MusicalTime | null; end: MusicalTime | null }, options: ReferenceComparisonOptions): ReferenceDimensionComparison {
  const currentIn = current.tempoShape.filter((item) => within(item.position, overlap))
  const referenceIn = reference.tempoShape.filter((item) => within(item.position, overlap))
  const referenceByKey = new Map(referenceIn.map((item) => [item.key, item]))
  const pairs = currentIn.flatMap((item) => { const other = referenceByKey.get(item.key); return other ? [{ current: item, reference: other }] : [] })
  if (!pairs.length) return unavailable('No shared tempo shape evidence exists in the overlapping score region.')
  const currentCenter = median(pairs.map((pair) => pair.current.logTempoRatio))
  const referenceCenter = median(pairs.map((pair) => pair.reference.logTempoRatio))
  const observations = pairs.map((pair) => observation('reference-tempo-shape', pair.current.key, pair.current.position, pair.current.measureNumbers, pair.current.logTempoRatio - currentCenter, pair.reference.logTempoRatio - referenceCenter, options.similarLogTempoDifference, options.noticeableLogTempoDifference, (difference, descriptor) => descriptor === 'very-similar' || descriptor === 'similar' ? 'Both takes use a similar local tempo shape here.' : difference > 0 ? 'Your take moves faster relative to its own global pace here.' : 'Your take stretches this point more than the reference.')).sort((a, b) => compareTime(a.position, b.position) || a.key.localeCompare(b.key))
  const denominator = Math.max(currentIn.length, referenceIn.length)
  const ratio = denominator ? observations.length / denominator : null
  const reliability = combineReliability(current.reliability.tempo, reference.reliability.tempo, observations.length, ratio ?? 0, options)
  const averageMagnitude = observations.reduce((sum, item) => sum + item.magnitude, 0) / observations.length
  return { status: 'ready', reliability, unavailableReason: null, coverage: { currentCount: currentIn.length, referenceCount: referenceIn.length, sharedCount: observations.length, ratio }, observations, summary: averageMagnitude <= options.similarLogTempoDifference ? 'Tempo shape is similar across the shared evidence.' : 'Tempo shape differs across parts of the shared score region.' }
}

export function pedalEngineVersionsAreComparable(current: InterpretationProfile, reference: InterpretationProfile): boolean {
  if (current.pedalGestures === null || reference.pedalGestures === null) return true
  const versions = (profile: InterpretationProfile) => [...new Set([profile.evidenceVersions.pedalAnalysis, ...profile.pedalGestures!.map((item) => item.engineVersion)].filter((value): value is string => typeof value === 'string'))]
  const currentVersions = versions(current)
  const referenceVersions = versions(reference)
  return currentVersions.length === 1 && referenceVersions.length === 1 && currentVersions[0] === referenceVersions[0]
}

export function compareInterpretations(input: CompareInterpretationsInput): ReferenceComparisonResult {
  const options = resolveReferenceComparisonOptions(input.options); const { current, reference } = input
  const emptyOverlap = { start: null, end: null }
  const build = (partial: Omit<ReferenceComparisonResult, 'id' | 'scoreVersionId' | 'currentAttemptOrRecordingId' | 'currentVoicingAnalysisId' | 'diagnostics'>): ReferenceComparisonResult => deepFreeze({ id: `reference-comparison:${stableHash(JSON.stringify({ current: current.attemptId, reference: reference?.attemptId ?? null, voicing: input.currentVoicingAnalysisId, engine: REFERENCE_COMPARISON_ENGINE_VERSION, options }))}`, scoreVersionId: current.scoreVersionId, currentAttemptOrRecordingId: current.attemptId || current.recordingId, currentVoicingAnalysisId: input.currentVoicingAnalysisId, ...partial, diagnostics: { referenceComparisonEngineVersion: REFERENCE_COMPARISON_ENGINE_VERSION, currentEngineVersions: current.evidenceVersions, referenceEngineVersions: reference?.evidenceVersions ?? {} } })
  if (!reference) { const dimension = unavailable('No interpretation reference is selected.'); return build({ status: 'unavailable', reliability: 'unavailable', unavailableReason: 'No interpretation reference is selected.', referenceAttemptId: null, referencePerformedAt: null, referencePracticeSpeed: null, referenceSchemaVersion: null, referenceEngineVersions: {}, overlapScope: emptyOverlap, tempo: dimension, dynamics: dimension, articulation: dimension, pedal: dimension, voicing: dimension, warnings: [] }) }
  const incompatible = current.attemptId === reference.attemptId || current.arrangementId !== reference.arrangementId || current.scoreVersionId !== reference.scoreVersionId || !samePartSelection(current.includedPartIds, reference.includedPartIds)
  const start = !current.scope.start ? reference.scope.start : !reference.scope.start ? current.scope.start : compareTime(current.scope.start, reference.scope.start) >= 0 ? current.scope.start : reference.scope.start
  const end = !current.scope.end ? reference.scope.end : !reference.scope.end ? current.scope.end : compareTime(current.scope.end, reference.scope.end) <= 0 ? current.scope.end : reference.scope.end
  const overlap = { start, end }; const noOverlap = start !== null && end !== null && compareTime(start, end) > 0
  if (incompatible || noOverlap) { const reason = incompatible ? 'The reference must be a different take from the same Arrangement, ScoreVersion, and part selection.' : 'The two grading scopes do not overlap.'; const dimension = unavailable(reason); return build({ status: 'unavailable', reliability: 'unavailable', unavailableReason: reason, referenceAttemptId: reference.attemptId, referencePerformedAt: reference.performedAt, referencePracticeSpeed: reference.practiceSpeed, referenceSchemaVersion: reference.schemaVersion, referenceEngineVersions: reference.evidenceVersions, overlapScope: overlap, tempo: dimension, dynamics: dimension, articulation: dimension, pedal: dimension, voicing: dimension, warnings: [{ code: incompatible ? 'REFERENCE_INCOMPATIBLE' : 'NO_SCOPE_OVERLAP', message: reason }] }) }
  const tempo = compareTempo(current, reference, overlap, options)
  const dynamics = compareKeyed(current.dynamicsGestures, reference.dynamicsGestures, overlap, (value) => value.value, (value) => [value.measureNumber], [current.reliability.dynamics, reference.reliability.dynamics], options, 'Dynamics', (difference, descriptor) => descriptor === 'very-similar' || descriptor === 'similar' ? 'Both takes shape this authored gesture similarly.' : difference > 0 ? 'Your take shapes this contrast more strongly.' : 'The reference shapes this contrast more strongly.')
  const articulation = compareKeyed(current.articulationGestures, reference.articulationGestures, overlap, (value) => value.value, (value) => [value.measureNumber], [current.reliability.articulation, reference.reliability.articulation], options, 'Articulation', (difference, descriptor) => descriptor === 'very-similar' || descriptor === 'similar' ? 'Both takes use similar physical key treatment here.' : difference > 0 ? 'Your take uses a longer or more separated treatment here.' : 'Your take uses a shorter or more connected treatment here.')
  const pedalCompatible = pedalEngineVersionsAreComparable(current, reference)
  const pedal = pedalCompatible ? compareKeyed(current.pedalGestures, reference.pedalGestures, overlap, (value) => value.relativeTimingMs, (value) => [value.measureNumber], [current.reliability.pedal, reference.reliability.pedal], options, 'Pedal', (difference, descriptor) => descriptor === 'very-similar' || descriptor === 'similar' ? 'Both takes coordinate this pedal gesture similarly with their own musical arrivals.' : difference > 0 ? 'You place this pedal gesture later relative to your harmonic arrival.' : 'You place this pedal gesture earlier relative to your harmonic arrival.', [35, 100]) : unavailable('These takes use different Pedal timing-engine semantics, so direct Pedal comparison is unavailable.')
  const voicing = compareKeyed(current.voicingGestures, reference.voicingGestures, overlap, (value) => value.focusAdvantage, (value) => [value.measureNumber], [current.reliability.voicing, reference.reliability.voicing], options, 'Voicing', (difference, descriptor) => descriptor === 'very-similar' || descriptor === 'similar' ? 'Both takes separate the configured voices similarly.' : difference > 0 ? 'Your configured foreground is more projected here.' : 'The reference keeps the configured foreground more projected here.')
  const dimensions = [tempo, dynamics, articulation, pedal, voicing]; const ready = dimensions.filter((dimension) => dimension.status === 'ready'); const reliability = ready.length ? ready.reduce((lowest, dimension) => rank(dimension.reliability) < rank(lowest) ? dimension.reliability : lowest, 'reliable' as ReferenceComparisonReliability) : 'unavailable'
  return build({ status: ready.length ? 'ready' : 'unavailable', reliability, unavailableReason: ready.length ? null : 'No shared interpretation evidence is available in the overlap.', referenceAttemptId: reference.attemptId, referencePerformedAt: reference.performedAt, referencePracticeSpeed: reference.practiceSpeed, referenceSchemaVersion: reference.schemaVersion, referenceEngineVersions: reference.evidenceVersions, overlapScope: overlap, tempo, dynamics, articulation, pedal, voicing, warnings: [] })
}
