import { GitCompareArrows, X } from 'lucide-react'
import { Button, StatusPill } from '../../components/ui'
import type { AttemptSummary } from '../persistence/types'
import type { ReferenceComparisonResult, ReferenceDimensionComparison } from './types'
import type { ReferenceComparisonState } from './useReferenceComparison'

function date(value: string): string { return new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) }
function Dimension({ name, value }: { name: string; value: ReferenceDimensionComparison }) { return <article><strong>{name}</strong><StatusPill tone="neutral">{value.status === 'ready' ? value.reliability : 'unavailable'}</StatusPill><p>{value.summary}</p>{value.observations[0] && <small>{value.observations[0].description}</small>}</article> }
function TempoShapeChart({ result }: { result: ReferenceComparisonResult }) { if (!result.tempo.observations.length) return null; const points = result.tempo.observations; const x = (index: number) => points.length === 1 ? 150 : 16 + index * 268 / (points.length - 1); const y = (value: number) => 55 - Math.max(-0.25, Math.min(0.25, value)) * 140; return <figure className="reference-tempo-chart"><svg viewBox="0 0 300 110" role="img" aria-labelledby="tempo-chart-title tempo-chart-desc"><title id="tempo-chart-title">Centered tempo-shape comparison</title><desc id="tempo-chart-desc">Current and reference local tempo shape across shared score positions, with global speed removed.</desc><line x1="12" y1="55" x2="288" y2="55" /><polyline className="current" points={points.map((item, index) => `${x(index)},${y(item.currentValue)}`).join(' ')} /><polyline className="reference" points={points.map((item, index) => `${x(index)},${y(item.referenceValue)}`).join(' ')} />{points.map((item, index) => <circle className="current" key={`current:${item.id}`} cx={x(index)} cy={y(item.currentValue)} r="2.5" />)}{points.map((item, index) => <circle className="reference" key={`reference:${item.id}`} cx={x(index)} cy={y(item.referenceValue)} r="2.5" />)}</svg><figcaption><span>Current — solid</span><span>Reference — dashed</span></figcaption></figure> }

export function ReferenceComparisonPanel({ analysis, candidates = [], selectedReferenceId, onSelectReference, readOnly = false }: { analysis: ReferenceComparisonState | { status: 'ready'; result: ReferenceComparisonResult }; candidates?: readonly AttemptSummary[]; selectedReferenceId?: string | null; onSelectReference?: (id: string | null) => Promise<void>; readOnly?: boolean }) {
  const result = analysis.status === 'ready' ? analysis.result : null
  return <section className="panel reference-comparison"><header><div><StatusPill tone="neutral"><GitCompareArrows /> Interpretation reference</StatusPill><h2>Compare saved interpretations</h2><p>Compare your interpretation with another saved take. Differences are descriptive, not grading targets.</p></div>{result?.referencePerformedAt && <span>{date(result.referencePerformedAt)} · {Math.round((result.referencePracticeSpeed ?? 1) * 100)}%</span>}</header>
    {!readOnly && <div className="reference-picker"><label><span>Saved take</span><select value={selectedReferenceId ?? ''} onChange={(event) => void onSelectReference?.(event.target.value || null)}><option value="">No reference selected</option>{candidates.map((candidate) => <option key={candidate.id} value={candidate.id}>{date(candidate.performedAt)} · {Math.round(candidate.practiceSpeedMultiplier * 100)}% · {candidate.gradingScope === 'full-plan' ? 'Full score' : 'Played section'}</option>)}</select></label>{selectedReferenceId && <Button variant="ghost" icon={X} onClick={() => void onSelectReference?.(null)}>Clear reference</Button>}</div>}
    {analysis.status === 'analyzing' && <div className="analysis-processing">Comparing interpretation profiles…</div>}{analysis.status === 'error' && <div className="expression-unavailable">{analysis.message}</div>}
    {result?.status === 'unavailable' ? <div className="voicing-empty"><strong>{result.unavailableReason}</strong></div> : result && <><div className="reference-dimensions"><Dimension name="Tempo shape" value={result.tempo} /><Dimension name="Dynamics" value={result.dynamics} /><Dimension name="Articulation" value={result.articulation} /><Dimension name="Pedal" value={result.pedal} /><Dimension name="Voicing" value={result.voicing} /></div><TempoShapeChart result={result} /></>}
    {!result && analysis.status === 'idle' && <div className="voicing-empty"><strong>Choose a saved take to compare interpretations.</strong></div>}
    <p className="pedal-caveat">A reference is another possible realization—not a correct answer, ideal performance, or quality score.</p>
  </section>
}
