import { centeredIntervalScores } from '../prepareEvidence'
import { facet, intervalObservation, pitchObservations, mean, type ModuleAnalysis, type TechniqueAnalyzerContext } from './shared'
export function analyzeJumps(context: TechniqueAnalyzerContext): ModuleAnalysis {
  const landingIndices = new Set(context.exercise.events.map((event, index) => event.role === 'landing' ? index : -1).filter((index) => index >= 0))
  const landing = pitchObservations(context, 'landing-accuracy', (index) => landingIndices.has(index))
  const jumpEvidence = context.evidence.intervals.filter((item) => item.transitionKind === 'jump-landing'), recoveryEvidence = context.evidence.intervals.filter((item) => item.transitionKind === 'jump-recovery')
  const jump = centeredIntervalScores(jumpEvidence, context.options.evennessLogTolerance).map((item) => intervalObservation('jump-timing-consistency', { ...item, value: item.centeredRatio }, 'jump-landing-interval', 'ratio', 'Only origin/recovery-to-distant-landing transitions contribute.'))
  const logs = recoveryEvidence.map((item) => item.logRatio).sort((a, b) => a - b), center = logs.length ? logs[Math.floor(logs.length / 2)]! : 0
  const recovery = recoveryEvidence.map((evidence) => { const ratio = Math.exp(evidence.logRatio - center), score = ratio <= context.options.pulseExpansionGraceRatio ? 100 : 100 * Math.max(0, 1 - (ratio - context.options.pulseExpansionGraceRatio) / (context.options.pulseExtremePauseRatio - context.options.pulseExpansionGraceRatio)); return intervalObservation('recovery-continuity', { evidence, score, value: ratio }, 'jump-recovery-interval', 'ratio', 'Only landing-to-immediate-nearby-recovery transitions contribute.') })
  const findings = mean(jump.map((item) => item.score)) !== null && mean(recovery.map((item) => item.score)) !== null && mean(jump.map((item) => item.score))! > mean(recovery.map((item) => item.score))! + context.options.comparativeFindingGap ? ['Distant arrivals were more consistent than motion immediately after landing.'] : []
  return { observations: [...landing, ...jump, ...recovery], findings, facets: [facet(context, { id: 'landing-accuracy', family: 'pitch', observations: landing, eligibleCount: landingIndices.size, minimumEvidence: context.options.minimumJumpTransitions, summary: 'Only authored distant LANDING events are pitch votes.' }), facet(context, { id: 'jump-timing-consistency', family: 'interval-precision', observations: jump, eligibleCount: jumpEvidence.length, minimumEvidence: context.options.minimumJumpTransitions, summary: 'Median-centered timing consistency of large-movement landing transitions only.' }), facet(context, { id: 'recovery-continuity', family: 'continuity', observations: recovery, eligibleCount: recoveryEvidence.length, minimumEvidence: context.options.minimumJumpTransitions, summary: 'Hesitation after landing, using a separate landing-to-recovery transition population.' })] }
}
