import { clamp01, median } from '../../timing-analysis/math'
import { facet, observationId, type ModuleAnalysis, type TechniqueAnalyzerContext } from './shared'
import type { LocalTempoSample } from '../../timing-analysis/types'
import type { TechniqueObservationV2 } from '../types'
function tempoObservation(facetId: TechniqueObservationV2['facetId'], sample: LocalTempoSample, score: number, value: number, method: TechniqueObservationV2['method'], summary: string): TechniqueObservationV2 { return { id: observationId(facetId, sample.id), facetId, expectedEventIds: [], expectedGroupIds: [sample.startExpectedGroupId, sample.endExpectedGroupId], performedGroupIds: [], sourceTimingObservationIds: [sample.id], sourceNoteResultIds: [], score, value, unit: 'ratio', method, summary } }
export function analyzeTempoControl(context: TechniqueAnalyzerContext): ModuleAnalysis {
  const samples = context.timingAnalysis.tempo.localSamples
  const target = samples.map((sample) => { const error = Math.abs(Math.log(sample.tempoRatio)); const score = 100 * clamp01(1 - error / context.options.tempoTargetLogTolerance); return tempoObservation('target-tempo-control', sample, score, sample.tempoRatio, 'target-tempo-ratio', 'Local performed tempo against its authored numeric target.') })
  const center = median(samples.map((sample) => Math.log(sample.tempoRatio))) ?? 0
  const stability = samples.map((sample) => { const centered = Math.log(sample.tempoRatio) - center; const score = 100 * clamp01(1 - Math.abs(centered) / context.options.tempoStabilityLogTolerance); return tempoObservation('tempo-stability', sample, score, Math.exp(centered), 'local-tempo-stability', 'Variation around the player’s own attempt-local technical tempo.') })
  const transition: TechniqueObservationV2[] = []
  for (let index = 1; index < samples.length; index += 1) { const previous = samples[index - 1]!, current = samples[index]!; const targetDelta = Math.log(current.targetQuarterBpm / previous.targetQuarterBpm); if (Math.abs(targetDelta) < context.options.minimumAuthoredTempoDelta) continue; const performedDelta = Math.log(current.performedQuarterBpm / previous.performedQuarterBpm); const score = 100 * clamp01(1 - Math.abs(performedDelta - targetDelta) / context.options.tempoTrajectoryLogTolerance); transition.push({ id: observationId('tempo-transition-control', `${previous.id}:${current.id}`), facetId: 'tempo-transition-control', expectedEventIds: [], expectedGroupIds: [previous.startExpectedGroupId, current.endExpectedGroupId], performedGroupIds: [], sourceTimingObservationIds: [previous.id, current.id], sourceNoteResultIds: [], score, value: performedDelta - targetDelta, unit: 'log-ratio', method: 'authored-tempo-trajectory', summary: 'Performed local tempo change compared with the actual authored numeric progression.' }) }
  return { observations: [...target, ...stability, ...transition], findings: [], facets: [facet(context, { id: 'target-tempo-control', family: 'tempo', observations: target, eligibleCount: samples.length, minimumEvidence: context.options.minimumTempoSamples, summary: 'Accuracy against requested numeric tempo; steady but off-target playing can score lower.' }), facet(context, { id: 'tempo-stability', family: 'tempo', observations: stability, eligibleCount: samples.length, minimumEvidence: context.options.minimumTempoStabilitySamples, summary: 'Variation around the performed local tempo, independent of target accuracy.' }), facet(context, { id: 'tempo-transition-control', family: 'tempo', observations: transition, eligibleCount: Math.max(0, samples.length - 1), minimumEvidence: context.options.minimumTempoTransitionSamples, summary: 'Agreement between performed and authored local numeric tempo progression; never the overall Tempo score.' })] }
}
