import { AlertCircle, Layers3, Plus, Settings2, Trash2 } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Button, StatusPill } from '../../components/ui'
import type { VoiceLane, VoicingAnalysisResult, VoicingIntentProfile, VoicingIntentRegion } from './types'
import type { VoicingAnalysisState } from './useVoicingAnalysis'
import { validateVoicingIntentProfile } from './voicingIntent'

function percent(value: number | null): string { return value === null ? '—' : `${Math.round(value * 100)}` }
function blankRegion(index: number, maxMeasure: number): VoicingIntentRegion { return { id: `voicing-region:${index + 1}`, startMeasureIndex: 0, endMeasureIndex: maxMeasure, foregroundLaneIds: [], supportLaneIds: [] } }

export function VoicingAnalysisPanel({ analysis, lanes, profile, scoreVersionId, maxMeasureIndex, onSaveProfile, onAnalyze, readOnly = false }: { analysis: VoicingAnalysisState | { status: 'ready'; result: VoicingAnalysisResult }; lanes: readonly VoiceLane[]; profile: VoicingIntentProfile | null; scoreVersionId: string; maxMeasureIndex: number; onSaveProfile?: (profile: VoicingIntentProfile | null) => Promise<void>; onAnalyze?: () => void; readOnly?: boolean }) {
  const [editing, setEditing] = useState(false); const [regions, setRegions] = useState<readonly VoicingIntentRegion[]>(profile?.regions ?? [blankRegion(0, maxMeasureIndex)]); const [error, setError] = useState<string | null>(null)
  const result = analysis.status === 'ready' ? analysis.result : null
  const candidate = useMemo<VoicingIntentProfile>(() => ({ id: profile?.id ?? `voicing-intent:${scoreVersionId}`, scoreVersionId, regions, updatedAt: new Date().toISOString() }), [profile?.id, regions, scoreVersionId])
  const toggleEditor = () => { if (editing) setEditing(false); else { setRegions(profile?.regions ?? [blankRegion(0, maxMeasureIndex)]); setEditing(true) } }
  const save = async () => { const errors = validateVoicingIntentProfile(candidate, lanes, scoreVersionId); if (errors.length) { setError(errors.join(' ')); return } try { await onSaveProfile?.(candidate); setEditing(false); setError(null) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Voicing focus could not be saved.') } }
  const toggle = (regionIndex: number, role: 'foregroundLaneIds' | 'supportLaneIds', laneId: string) => setRegions((current) => current.map((region, index) => index !== regionIndex ? region : { ...region, [role]: region[role].includes(laneId) ? region[role].filter((id) => id !== laneId) : [...region[role], laneId] }))
  return <section className="panel voicing-analysis"><header><div><StatusPill tone={result?.status === 'ready' ? 'violet' : 'neutral'}><Layers3 /> Voicing</StatusPill><h2>Foreground projection</h2><p>Measures relative MIDI attack balance between the foreground and support voices you choose.</p></div><strong className="pedal-score">{percent(result?.score ?? null)}</strong></header>
    {!result && analysis.status === 'idle' && <div className="expression-unavailable"><AlertCircle />Analyze the take to inspect score voices.</div>}
    {analysis.status === 'analyzing' && <div className="analysis-processing">Preparing Voicing evidence…</div>}
    {analysis.status === 'error' && <div className="expression-unavailable"><AlertCircle />{analysis.message}</div>}
    {result && <><div className="pedal-summary"><StatusPill tone={result.reliability === 'reliable' ? 'positive' : result.reliability === 'unavailable' ? 'neutral' : 'warning'}>{result.reliability}</StatusPill><span>{result.coverage.analyzedTargetCount} / {result.coverage.configuredTargetCount} configured balance events analyzed</span></div>{result.mode === 'descriptive' ? <div className="voicing-empty"><strong>No foreground focus configured.</strong><p>Detected score voices are shown without guessing which one is melody.</p></div> : result.observations.length ? <div className="expression-findings">{result.observations.slice(0, 3).map((item) => <span key={item.id}>{item.summary} <small>m. {item.measureNumber}</small></span>)}</div> : <div className="expression-unavailable"><AlertCircle />{result.unavailableReason}</div>}<div className="voicing-lanes">{result.laneStatistics.map((stat) => { const lane = result.lanes.find((item) => item.id === stat.laneId)!; return <div key={stat.laneId}><strong>{lane.label}</strong><span>{stat.sampleCount} matched attacks · median {stat.medianNormalizedIntensity === null ? 'unavailable' : stat.medianNormalizedIntensity.toFixed(2)}</span></div> })}</div></>}
    {!readOnly && <div className="voicing-actions"><Button variant="secondary" icon={Settings2} onClick={toggleEditor}>{profile ? 'Edit voicing focus' : 'Configure voicing focus'}</Button>{profile && <Button variant="ghost" icon={Trash2} onClick={() => void onSaveProfile?.(null)}>Clear configuration</Button>}{onAnalyze && <Button variant="ghost" onClick={onAnalyze}>Analyze voicing</Button>}</div>}
    {editing && <div className="voicing-editor"><p>Choose musical roles explicitly. Clef never infers melody from pitch, staff, hand, or voice number.</p>{regions.map((region, regionIndex) => <fieldset key={region.id}><legend>Region {regionIndex + 1}</legend><div className="voicing-range"><label>Start measure<input type="number" min={1} max={maxMeasureIndex + 1} value={region.startMeasureIndex + 1} onChange={(event) => setRegions((current) => current.map((item, index) => index === regionIndex ? { ...item, startMeasureIndex: Number(event.target.value) - 1 } : item))} /></label><label>End measure<input type="number" min={1} max={maxMeasureIndex + 1} value={region.endMeasureIndex + 1} onChange={(event) => setRegions((current) => current.map((item, index) => index === regionIndex ? { ...item, endMeasureIndex: Number(event.target.value) - 1 } : item))} /></label></div><div className="voicing-role-grid"><div><strong>Foreground</strong>{lanes.map((lane) => <label key={lane.id}><input type="checkbox" checked={region.foregroundLaneIds.includes(lane.id)} disabled={lane.ambiguous} onChange={() => toggle(regionIndex, 'foregroundLaneIds', lane.id)} />{lane.label}</label>)}</div><div><strong>Support</strong>{lanes.map((lane) => <label key={lane.id}><input type="checkbox" checked={region.supportLaneIds.includes(lane.id)} disabled={lane.ambiguous} onChange={() => toggle(regionIndex, 'supportLaneIds', lane.id)} />{lane.label}</label>)}</div></div>{regions.length > 1 && <Button variant="ghost" icon={Trash2} onClick={() => setRegions((current) => current.filter((_, index) => index !== regionIndex))}>Remove region</Button>}</fieldset>)}{error && <div className="practice-build-error">{error}</div>}<div className="voicing-actions"><Button variant="secondary" icon={Plus} onClick={() => setRegions((current) => [...current, blankRegion(current.length, maxMeasureIndex)])}>Add region</Button><Button onClick={() => void save()}>Save focus</Button></div></div>}
    <p className="pedal-caveat">MIDI attack balance, not acoustic loudness, timbre, or objective musical quality.</p>
  </section>
}
