import { Activity, AlertCircle, Gauge, RefreshCw, ScanSearch, Sparkles, Volume2 } from 'lucide-react'
import { Button, StatusPill } from '../../components/ui'
import type { ExpressionAnalysisState } from './useExpressionAnalysis'
import type { ArticulationAnalysis, DynamicsAnalysis, ExpressionReliability } from './types'

function percent(value: number | null): string { return value === null ? '—' : (value * 100).toFixed(1) }

function reliabilityTone(reliability: ExpressionReliability): 'positive' | 'warning' | 'neutral' {
  return reliability === 'reliable' ? 'positive' : reliability === 'limited' || reliability === 'provisional' ? 'warning' : 'neutral'
}

function DynamicsCard({ result }: { result: DynamicsAnalysis }) {
  const ordered = [...result.observations].sort((left, right) => left.score - right.score || left.id.localeCompare(right.id))
  return <article className="expression-card dynamics-card"><header><span><Volume2 /><small>Relative MIDI dynamics</small><strong>Dynamics</strong></span><b>{percent(result.score)}</b></header><StatusPill tone={reliabilityTone(result.reliability)}>{result.reliability}</StatusPill><p>{result.coverage.analyzedTargetCount} / {result.coverage.authoredTargetCount} authored targets analyzed</p>{result.status === 'unavailable' ? <div className="expression-unavailable"><AlertCircle />{result.unavailableReason}</div> : <div className="expression-findings">{ordered.at(-1) && <span className="success"><Sparkles />{ordered.at(-1)!.summary}</span>}{ordered[0] && <span className="issue"><Activity />{ordered[0]!.summary}</span>}</div>}<details><summary>Velocity interpretation</summary><p>Contrast is normalized once across correct matched notes in this take using robust Q10–Q90 velocity evidence. It is not an absolute p/mf/f mapping.</p><dl><div><dt>Matched samples</dt><dd>{result.diagnostics.normalization.sampleCount}</dd></div><div><dt>Q10 / Q90</dt><dd>{result.diagnostics.normalization.q10?.toFixed(1) ?? '—'} / {result.diagnostics.normalization.q90?.toFixed(1) ?? '—'}</dd></div><div><dt>Changes / wedges / accents</dt><dd>{result.diagnostics.explicitChangeCount} / {result.diagnostics.wedgeCount} / {result.diagnostics.accentCount}</dd></div></dl></details></article>
}

function ArticulationCard({ result }: { result: ArticulationAnalysis }) {
  const ordered = [...result.observations].sort((left, right) => left.score - right.score || left.id.localeCompare(right.id))
  return <article className="expression-card articulation-card"><header><span><Gauge /><small>Physical key articulation</small><strong>Articulation</strong></span><b>{percent(result.score)}</b></header><StatusPill tone={reliabilityTone(result.reliability)}>{result.reliability}</StatusPill><p>{result.coverage.analyzedTargetCount} / {result.coverage.authoredTargetCount} authored targets analyzed</p>{result.status === 'unavailable' ? <div className="expression-unavailable"><AlertCircle />{result.unavailableReason}</div> : <div className="expression-findings">{ordered.at(-1) && <span className="success"><Sparkles />{ordered.at(-1)!.summary}</span>}{ordered[0] && <span className="issue"><Activity />{ordered[0]!.summary}</span>}</div>}<details><summary>Key-release interpretation</summary><p>Clef measures attack-to-physical-release gate ratios and slur transitions. Sustain pedal can change the audible result; pedal technique is not graded here.</p><dl><div><dt>Gate / legato targets</dt><dd>{result.diagnostics.gateTargetCount} / {result.diagnostics.legatoTargetCount}</dd></div><div><dt>Missing releases</dt><dd>{result.diagnostics.missingReleaseCount}</dd></div><div><dt>Pedal-affected observations</dt><dd>{result.diagnostics.pedalAffectedCount}</dd></div></dl></details></article>
}

export function ExpressionAnalysisPanel({ analysis, onAnalyze, readOnly = false }: { analysis: ExpressionAnalysisState; onAnalyze: () => void; readOnly?: boolean }) {
  if (analysis.status === 'idle') return <section className="panel expression-state"><div><Sparkles /><span><small>Phase 9 expression</small><strong>Analyze dynamics and articulation</strong><p>Use authored notation, correct note correspondences, MIDI velocity, and physical key releases.</p></span></div><Button icon={Sparkles} onClick={onAnalyze}>Analyze expression</Button></section>
  if (analysis.status === 'analyzing') return <section className="panel expression-state"><div><ScanSearch className="spin" /><span><small>Expression analysis</small><strong>Mapping authored expression</strong><p>Building performance-relative dynamics and tempo-aware key-articulation evidence.</p></span></div><StatusPill tone="violet">Processing</StatusPill></section>
  if (analysis.status === 'error') return <section className="panel expression-state unavailable"><div><AlertCircle /><span><small>Expression unavailable</small><strong>Analysis could not be completed</strong><p>{analysis.message}</p></span></div>{!readOnly && <Button variant="secondary" icon={RefreshCw} onClick={onAnalyze}>Retry</Button>}</section>
  return <section className="panel expression-analysis"><header><div><StatusPill tone={analysis.result.status === 'ready' ? 'violet' : 'neutral'}><Sparkles /> {readOnly ? 'Saved expression snapshot' : 'Expression ready'}</StatusPill><h2>Expression</h2><p>Dynamics and Articulation are independent evidence dimensions. They are not an overall performance or musicality score.</p></div></header><div className="expression-grid"><DynamicsCard result={analysis.result.dynamics} /><ArticulationCard result={analysis.result.articulation} /></div><details className="results-diagnostics"><summary>Expression methodology</summary><div><span>Engine <strong>{analysis.result.diagnostics.expressionAnalysisEngineVersion}</strong></span><span>Parser <strong>{analysis.result.diagnostics.musicXmlParserVersion}</strong></span><span>Correct matches <strong>{analysis.result.diagnostics.correctlyMatchedObservationCount}</strong></span><span>Scope <strong>{analysis.result.scope.type}</strong></span></div></details></section>
}
